name: Push to staging sends dispatch event

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  dispatch:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch event
        run: |
           curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/OWNER/REPO/dispatches \
                -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'