name: Push to staging sends dispatch event

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  dispatch:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    permissions: write-all

                # -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
    steps:
      - name: Send repository dispatch event
        run: |
           curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/aziaziazi/multiples-github-pages/dispatches -d '{"event_type": "staging_push"}'               
